export interface User { id: string; email: string; name: string; role: 'admin' | 'seller' | 'customer'; avatar?: string }
export interface Seller { id: string; userId: string; storeName: string; slug: string; rating: number; verified: boolean; logo?: string; banner?: string; description?: string; policies?: Record<string, string> }
export interface Category { id: string; name: string; slug: string; image?: string; parentId?: string }
export interface Product { id: string; sellerId: string; categoryId: string; name: string; slug: string; description: string; shortDescription?: string; price: number; salePrice?: number; cost?: number; sku?: string; barcode?: string; weight?: number; dimensions?: string; images: string[]; video?: string; tags: string[]; attributes?: Record<string, string>; inventory: number; reserved: number; lowStock: number; featured?: boolean; bestseller?: boolean; newArrival?: boolean; deal?: boolean; sponsored?: boolean; seoTitle?: string; metaDescription?: string; createdAt: string }
export interface CartItem { productId: string; quantity: number; variantId?: string }
export interface Order { id: string; customerId: string; items: { productId: string; quantity: number; price: number }[]; subtotal: number; tax: number; shipping: number; discount: number; total: number; status: 'pending'|'processing'|'shipped'|'delivered'|'cancelled'|'refunded'; channel: 'ant'|'etsy'|'ebay'|'shopify'; paymentMethod: string; shippingAddress: Record<string, string>; createdAt: string }
export interface Review { id: string; productId: string; customerId: string; rating: number; text?: string; images?: string[]; verified: boolean; helpful: number; response?: string; createdAt: string }
export interface Coupon { id: string; code: string; type: 'percent'|'fixed'; value: number; minOrder?: number; maxUses?: number; used: number; startsAt?: string; endsAt?: string; active: boolean }
export interface Banner { id: string; title?: string; subtitle?: string; image: string; link?: string; active: boolean; position: number }
export interface HomepageSection { id: string; type: string; title?: string; data: Record<string, unknown>; visible: boolean; position: number }
export interface SiteSettings { id: string; storeName: string; logo?: string; colors: Record<string, string>; fonts: Record<string, string>; seo: Record<string, string>; socials: Record<string, string>; currency: string; contactEmail?: string; contactPhone?: string; address?: string }
